services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    container_name: web
    environment:
      - DJANGO_SETTINGS_MODULE=netology_pd_diplom.settings
    command: >
      sh -c "python /app/reference/netology_pd_diplom/manage.py migrate &&
             python /app/reference/netology_pd_diplom/manage.py collectstatic --noinput &&
             python /app/reference/netology_pd_diplom/manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - redis

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    container_name: celery
    environment:
      - DJANGO_SETTINGS_MODULE=netology_pd_diplom.settings
      - PYTHONPATH=/app/reference/netology_pd_diplom
      - CELERY_BROKER_URL=redis://redis:6379/0
    working_dir: /app/reference/netology_pd_diplom
    command: celery -A netology_pd_diplom worker --loglevel=info
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
